// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// corr_aggregate_cpp
arma::cube corr_aggregate_cpp(const Rcpp::List& coords, const Rcpp::List& weights, const arma::vec& phi, double kappa, bool weighted, int nthreads);
RcppExport SEXP _SDALGCP2_corr_aggregate_cpp(SEXP coordsSEXP, SEXP weightsSEXP, SEXP phiSEXP, SEXP kappaSEXP, SEXP weightedSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< bool >::type weighted(weightedSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(corr_aggregate_cpp(coords, weights, phi, kappa, weighted, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// cross_cov_cpp
arma::mat cross_cov_cpp(const arma::mat& pred, const Rcpp::List& coords, const Rcpp::List& weights, double phi, double kappa, bool weighted, int nthreads);
RcppExport SEXP _SDALGCP2_cross_cov_cpp(SEXP predSEXP, SEXP coordsSEXP, SEXP weightsSEXP, SEXP phiSEXP, SEXP kappaSEXP, SEXP weightedSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type pred(predSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< bool >::type weighted(weightedSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cross_cov_cpp(pred, coords, weights, phi, kappa, weighted, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// set_omp_num_threads
void set_omp_num_threads(int n);
RcppExport SEXP _SDALGCP2_set_omp_num_threads(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    set_omp_num_threads(n);
    return R_NilValue;
END_RCPP
}
// corr_and_grad_cpp
Rcpp::List corr_and_grad_cpp(const Rcpp::List& coords, const Rcpp::List& weights, double phi, double kappa, bool weighted, int nthreads);
RcppExport SEXP _SDALGCP2_corr_and_grad_cpp(SEXP coordsSEXP, SEXP weightsSEXP, SEXP phiSEXP, SEXP kappaSEXP, SEXP weightedSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< bool >::type weighted(weightedSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(corr_and_grad_cpp(coords, weights, phi, kappa, weighted, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// laplace_mode_poisson_cpp
Rcpp::List laplace_mode_poisson_cpp(const arma::vec& y, const arma::vec& m, const arma::vec& mu, const arma::mat& Sigma, double tol, int maxit);
RcppExport SEXP _SDALGCP2_laplace_mode_poisson_cpp(SEXP ySEXP, SEXP mSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(laplace_mode_poisson_cpp(y, m, mu, Sigma, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// mala_poisson_cpp
Rcpp::List mala_poisson_cpp(const arma::vec& y, const arma::vec& m, const arma::vec& mu, const arma::mat& Sigma, const arma::vec& mode, const arma::mat& Sigma_tilde, int n_sim, int burnin, int thin, double h_init, double c1, double c2);
RcppExport SEXP _SDALGCP2_mala_poisson_cpp(SEXP ySEXP, SEXP mSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP modeSEXP, SEXP Sigma_tildeSEXP, SEXP n_simSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP h_initSEXP, SEXP c1SEXP, SEXP c2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_tilde(Sigma_tildeSEXP);
    Rcpp::traits::input_parameter< int >::type n_sim(n_simSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< double >::type h_init(h_initSEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type c2(c2SEXP);
    rcpp_result_gen = Rcpp::wrap(mala_poisson_cpp(y, m, mu, Sigma, mode, Sigma_tilde, n_sim, burnin, thin, h_init, c1, c2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SDALGCP2_corr_aggregate_cpp", (DL_FUNC) &_SDALGCP2_corr_aggregate_cpp, 6},
    {"_SDALGCP2_cross_cov_cpp", (DL_FUNC) &_SDALGCP2_cross_cov_cpp, 7},
    {"_SDALGCP2_set_omp_num_threads", (DL_FUNC) &_SDALGCP2_set_omp_num_threads, 1},
    {"_SDALGCP2_corr_and_grad_cpp", (DL_FUNC) &_SDALGCP2_corr_and_grad_cpp, 6},
    {"_SDALGCP2_laplace_mode_poisson_cpp", (DL_FUNC) &_SDALGCP2_laplace_mode_poisson_cpp, 6},
    {"_SDALGCP2_mala_poisson_cpp", (DL_FUNC) &_SDALGCP2_mala_poisson_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_SDALGCP2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
