# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Aggregated correlation array (C++)
#'
#' @param coords list of length N; element i is an n_i x 2 numeric matrix of
#'   candidate-point coordinates inside region i.
#' @param weights list of length N of weight vectors (each summing to 1), or an
#'   empty list for the unweighted (mean) case.
#' @param phi numeric vector of spatial scale parameters.
#' @param kappa Matern smoothness (0.5, 1.5 or 2.5 use closed forms).
#' @param weighted logical; TRUE for population-weighted aggregation.
#' @param nthreads number of OpenMP threads (<=0 uses the OpenMP default).
#' @return a numeric array of dimension N x N x length(phi).
#' @keywords internal
corr_aggregate_cpp <- function(coords, weights, phi, kappa, weighted, nthreads = 0L) {
    .Call(`_SDALGCP2_corr_aggregate_cpp`, coords, weights, phi, kappa, weighted, nthreads)
}

#' Aggregated cross-covariance between prediction points and regions (C++)
#'
#' Mirrors compute_cross_cov() for continuous prediction (bottleneck B5):
#' returns an n_pred x N matrix with entries
#'   sum_l w_jl * matern(||x_pred - x_jl||, phi, kappa)  (weighted) or the mean.
#' @param pred n_pred x 2 matrix of prediction coordinates.
#' @param coords list of N region point matrices.
#' @param weights list of N weight vectors, or empty for unweighted.
#' @param phi single spatial scale parameter.
#' @param kappa Matern smoothness.
#' @param weighted logical.
#' @param nthreads OpenMP threads (<=0 default).
#' @keywords internal
cross_cov_cpp <- function(pred, coords, weights, phi, kappa, weighted, nthreads = 0L) {
    .Call(`_SDALGCP2_cross_cov_cpp`, pred, coords, weights, phi, kappa, weighted, nthreads)
}

#' Aggregated correlation and its phi-derivatives at one phi (C++, Matern)
#'
#' @param coords list of N candidate-point matrices (n_i x 2).
#' @param weights list of N weight vectors (each summing to 1), or empty for the
#'   unweighted (mean) case.
#' @param phi spatial scale (> 0).
#' @param kappa Matern smoothness; one of 0.5, 1.5, 2.5.
#' @param weighted logical; population-weighted aggregation.
#' @param nthreads OpenMP threads (<= 0 = default).
#' @return list with N x N matrices \code{R}, \code{dR} (dR/dphi) and \code{d2R}
#'   (d2R/dphi2).
#' @keywords internal
corr_and_grad_cpp <- function(coords, weights, phi, kappa, weighted, nthreads = 0L) {
    .Call(`_SDALGCP2_corr_and_grad_cpp`, coords, weights, phi, kappa, weighted, nthreads)
}

#' Conditional mode and Laplace covariance for [S | Y], Poisson, non-nested (C++)
#'
#' @param y count vector.
#' @param m offset vector (e.g. expected counts / population).
#' @param mu prior mean vector of the latent field.
#' @param Sigma prior covariance matrix.
#' @param tol convergence tolerance on the gradient infinity-norm.
#' @param maxit maximum Newton iterations.
#' @return list with \code{mode} and \code{Sigma_tilde}.
#' @keywords internal
laplace_mode_poisson_cpp <- function(y, m, mu, Sigma, tol = 1e-8, maxit = 100L) {
    .Call(`_SDALGCP2_laplace_mode_poisson_cpp`, y, m, mu, Sigma, tol, maxit)
}

#' Adaptive MALA sampler for [S | Y], Poisson, non-nested (C++)
#'
#' Draw order per iteration is \code{d} normals then one uniform, giving
#' reproducible results under a common seed and the same mode/Sigma.tilde.
#'
#' @param y,m,mu,Sigma data and prior as in \code{laplace_mode_poisson_cpp}.
#' @param mode,Sigma_tilde Laplace mode and covariance (preconditioner).
#' @param n_sim,burnin,thin MCMC length controls.
#' @param h_init initial step size; if not finite, \code{1.65 / d^(1/6)} is used.
#' @param c1,c2 step-size adaptation constants.
#' @return list with \code{samples} (kept x d matrix of S draws) and \code{h}.
#' @keywords internal
mala_poisson_cpp <- function(y, m, mu, Sigma, mode, Sigma_tilde, n_sim, burnin, thin, h_init, c1, c2) {
    .Call(`_SDALGCP2_mala_poisson_cpp`, y, m, mu, Sigma, mode, Sigma_tilde, n_sim, burnin, thin, h_init, c1, c2)
}

